import React from 'react';

function GameImage() {
  const IMAGE_URL = 'https://i.imgur.com/N4wefbX.jpg';

  return (
    <div>
      <h1>GAME IMAGE</h1>
      {/* 
          The Loc Nar by Egor Klyuchnyk
          Instagram https://www.instagram.com/ad.2.222/
          Patreon https://www.patreon.com/Egor
          Buy his poster https://anomaly-world.com/posters-by-anomaly-world/cyberpunk-poster-ad2222
          */}
      <img src={IMAGE_URL} useMap="#the-loc-nar" alt="the loc nar" />
      {/* Image Map Generated by http://www.image-map.net/  */}
      <map name="the-loc-nar">
        {/* Easy */}
        <area
          target="_self"
          alt="Bowser"
          title="Bowser"
          href="#"
          coords="1578,3360,1779,3537"
          shape="rect"
        />
        <area
          target="_self"
          alt="Cacodemon"
          title="Cacodemon"
          href="#"
          coords="362,5155,583,5383"
          shape="rect"
        />
        {/* Medium */}
        <area
          target="_self"
          alt="Waldo"
          title="Waldo"
          href="#"
          coords="1663,7058,1611,6989"
          shape="rect"
        />
        <area
          target="_self"
          alt="Yubaba"
          title="Yubaba"
          href="#"
          coords="1005,436,1071,537"
          shape="rect"
        />
        {/* Hard */}
        <area
          target="_self"
          alt="Ash Ketchum"
          title="Ash Ketchum"
          href="#"
          coords="39,7318,85,7380"
          shape="rect"
        />
        <area
          target="_self"
          alt="Hollow Knight"
          title="Hollow Knight"
          href="#"
          coords="1177,7726,1212,7784"
          shape="rect"
        />
      </map>
    </div>
  );
}

export default GameImage;
